<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/11/1
 * Time: 14:49
 */

namespace app\admin\controller;


use think\Controller;
use think\Db;
use think\Request;
use think\Validate;

class Cate extends Base
{
    protected $model;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->model = Db::name('Cate');
    }

    public function index()
    {
        $result = $this->model->order('id', 'desc')->paginate();
        return $this->fetch('', [
            'result' => $result,
        ]);
    }

    /**
     * @param Request $request
     * @return mixed|void
     * 添加管理员
     */
    public function add(Request $request)
    {
        if ($request->isPost()) {
            $data = [
                'catename' => input('catename'),
                'status' => '1'
            ];
            $validate = new \app\admin\validate\Cate;
            if (!$validate->scene('add')->check($data)) {
                $this->error($validate->getError());
                die();
            }
            if ($this->model->insert($data)) {
                return $this->success('添加栏目成功', 'index');
            } else {
                return $this->error('添加栏目失败');
            }
        };
        return $this->fetch();
    }

    public function edit($id, Request $request)
    {
        $result = $this->model->where('id', $id)->find();
        if ($request->isPost()) {
            $data = [
                'id' => input('id'),
                'catename' => input('catename'),
            ];
            $validate = new \app\admin\validate\Cate;
            if (!$validate->scene('edit')->check($data)) {
                $this->error($validate->getError());
                die();
            }
            if ($this->model->update($data)) {
                return $this->success('修改栏目成功', 'index');
            } else {
                return $this->error('链接栏目失败');
            }
        };
        return $this->fetch('', [
            'result' => $result
        ]);
    }

    /**
     * 删除管理员
     * @param $id  删除的id
     * @throws \think\Exception
     * @throws \think\exception\PDOException
     */
    public function status($id,$status)
    {
        if ($this->model->where('id', $id)->update(['status' => $status])) {
            return $this->success('修改状态成功', 'index');
        } else {
            return $this->error('修改状态失败');
        }

    }
}