<?php

namespace app\index\controller;

use think\Controller;
use think\Db;

class Common extends Controller
{
    public function initialize()
    {
        $this->right();
        parent::initialize(); // TODO: Change the autogenerated stub
        $navDate = Db::name('cate')->where('status', '1')->order('id', 'desc')->select();
        $this->assign('navDate',$navDate);
    }

    public function right(){
        $clickres=Db::name('article')->order('click desc')->limit(10)->select();
        $tjres=Db::name('article')->where('status','=',1)->order('click desc')->limit(10)->select();
        $this->assign(array(
            'clickres'=>$clickres,
            'tjres'=>$tjres
        ));
    }
}
